---
title: "enactment_year_data"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```

# Code in year of enactment

```{r}
state_vec <- c("Alabama",
            "Arizona",
            "Arkansas",
            "California",
            "Colorado",
            "Connecticut",
            "Delaware",
            "Florida",
            "Georgia",
            "Idaho",
            "Illinois",
            "Indiana",
            "Iowa",
            "Kansas",
            "Kentucky",
            "Louisiana",
            "Maine",
            "Maryland",
            "Massachusetts",
            "Michigan",
            "Minnesota",
            "Mississippi",
            "Missouri",
            "Montana",
            "Nebraska",
            "Nevada",
            "New Hampshire",
            "New Jersey",
            "New Mexico",
            "New York",
            "North Carolina",
            "North Dakota",
            "Ohio",
            "Oklahoma",
            "Oregon",
            "Pennsylvania",
            "Rhode Island",
            "South Carolina",
            "South Dakota",
            "Tennessee",
            "Texas",
            "Utah",
            "Vermont",
            "Virginia",
            "Washington",
            "West Virginia",
            "Wisconsin",
            "Wyoming")
```

```{r}
Accountants <- tibble(
  occ = rep("Accountants", 48),
  state = state_vec,
  year = c(1919, 1919, 1915, 1901,
           1907, 1907, 1913, 1951,
           1908, 1917, 1903, 1915,
           1915, 1915, 1916, 1908,
           1913, 1900, 1909, 1905,
           1909, 1920, 1909, 1909,
           1909, 1913, 1917, 1904,
           1921, 1896, 1913, 1913,
           1908, 1917, 1915, 1906,
           1906, 1915, 1917, 1913,
           1915, 1907, 1912, 1910,
           1903, 1911, 1913, 1911),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Architects <- tibble(
  occ = rep("Architects", 48),
  state = state_vec,
  year = c(1931, 1921, 1941, 1901,
           1909, 1933, 1933, 1915,
           1919, 1917, 1897, 1929,
           1927, 1949, 1930, 1910,
           1945, 1935, NA, 1915,
           1921, 1928, 1941, 1917,
           1937, 1949, 1947, 1902,
           1931, 1915, 1915, 1913,
           1931, 1925, 1919, 1936,
           1936, 1917, 1925, 1921,
           1937, 1921, 1951, 1920,
           1903, 1921, 1917, 1951),
  enact = c(0,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,0,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Barbers <- tibble(
  occ = rep("Barbers", 48),
  state = state_vec,
  year = c(NA, 1928, 1937, 1927,
           1909, 1902, 1901, 1931,
           1914, 1927, 1909, 1933,
           1927, 1903, 1902, 1928,
           1933, 1904, 1931, NA,
           1897, 1930, 1921, 1929,
           1927, NA, 1937, 1933,
           1937, 1946, 1929, 1901,
           1933, 1931, 1899, 1903,
           1903, 1937, 1927, 1929,
           1929, 1903, 1937, NA,
           1901, 1933, 1935, 1931),
  enact = c(0,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,0,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1,
         yrLength = ifelse(enact == 0, max(yrLength, na.rm = TRUE), yrLength))
```

```{r}
Beauticians <- tibble(
  occ = rep("Beauticians", 48),
  state = state_vec,
  year = c(NA, 1928, 1947, 1927,
           1931, 1927, NA, 1935,
           1914, 1929, 1925, 1935,
           1927, 1927, 1932, 1924,
           1933, 1935, 1935, 1931,
           1927, 1948, 1929, 1929,
           1929, 1931, 1937, 1936,
           1925, 1946, 1933, 1927,
           1933, 1935, 1927, 1933,
           1926, 1933, 1927, 1939,
           1935, 1925, 1937, NA,
           1927, 1933, 1925, 1937),
  enact = c(0,1,1,1,
            1,1,0,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,0,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1,
         yrLength = ifelse(enact == 0, max(yrLength, na.rm = TRUE), yrLength))
```

```{r}
Chiropodists <- tibble(
  occ = rep("Chiropodists", 48),
  state = state_vec,
  year = c(NA, 1941, 1923, 1907,
           1915, 1915, 1923, 1931,
           1933, 1925, NA, 1925,
           1921, 1927, 1920, 1916,
           1933, 1916, NA, NA,
           1917, 1938, 1919, 1935,
           1919, 1917, 1919, 1908,
           1939, 1895, 1919, 1929,
           1916, 1935, 1925, 1913,
           1917, NA, 1931, 1931,
           1923, 1931, 1917, 1916,
           1917, NA, 1917, 1937),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Chiropractors <- tibble(
  occ = rep("Chiropractors", 48),
  state = state_vec,
  year = c(1911, 1921, 1915, 1922,
           1933, 1917, 1937, 1919,
           1921, 1919, 1899, 1927,
           1921, 1913, 1928, NA,
           1923, 1920, NA, 1933,
           1919, NA, 1927, 1917,
           1915, 1923, 1921, 1923,
           1921, NA, 1917, 1915,
           1916, 1921, 1915, 1913,
           1927, 1934, 1921, 1923,
           1949, 1921, 1919, 1913,
           1919, 1925, 1925, 1929),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,0,
            1,1,0,1,
            1,0,1,1,
            1,1,1,1,
            1,0,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1,
         yrLength = ifelse(enact == 0, max(yrLength, na.rm = TRUE), yrLength))
```

```{r}
Dentists <- tibble(
  occ = rep("Dentists", 48),
  state = state_vec,
  year = c(1881, 1913, 1887, 1885,
           1889, 1893, 1885, 1887,
           1920, 1919, 1881, 1887,
           1900, 1903, 1878, 1880,
           1891, 1884, 1887, 1883,
           1885, 1892, 1917, 1895,
           1905, 1895, 1895, 1890,
           1893, 1868, 1935, 1885,
           1868, 1890, 1887, 1876,
           1888, 1875, 1901, 1925,
           1889, 1909, 1882, 1887,
           1888, 1881, 1885, 1905),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Embalmers <- tibble(
  occ = rep("Embalmers", 48),
  state = state_vec,
  year = c(1915, 1909, 1909, 1915,
           1918, 1903, NA, 1917,
           1937, 1909, 1905, NA,
           1898, 1907, 1904, 1914,
           NA, 1902, NA, NA,
           1898, 1912, 1895, 1915,
           1931, 1909, 1935, 1927,
           NA, NA, 1901, 1899,
           1902, 1905, 1921, NA,
           1908, NA, NA, 1909,
           1903, 1921, 1910, 1897,
           NA, 1923, 1933, 1913),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Engineers <- tibble(
  occ = rep("Engineers", 48),
  state = state_vec,
  year = c(1935, 1921, 1925, 1929,
           1919, 1935, 1941, 1917,
           1937, 1918, 1941, 1921,
           1919, 1947, 1938, 1908,
           1935, 1939, 1941, 1919,
           1921, 1928, 1941, 1947,
           1937, 1919, 1945, 1921,
           1935, 1920, 1921, 1943,
           1933, 1935, 1919, 1921,
           1938, 1922, 1925, 1921,
           1937, 1935, 1939, 1920,
           1935, 1921, 1917, 1925),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Nurses <- tibble(
  occ = rep("Nurses", 48),
  state = state_vec,
  year = c(1915, 1921, 1913, 1905,
           1905, 1905, 1909, 1913,
           1907, 1911, 1907, 1905,
           1907, 1913, 1914, 1912,
           1915, 1904, 1910, 1909,
           1907, 1914, 1921, 1913,
           1909, 1933, 1907, 1912,
           1923, 1903, 1917, 1915,
           1915, 1909, 1911, 1909,
           1912, 1919, 1917, 1915,
           1909, 1917, 1910, 1903,
           1909, 1907, 1911, 1909),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Optometrists <- tibble(
  occ = rep("Optometrists", 48),
  state = state_vec,
  year = c(1919, 1925, 1915, 1903,
           1925, 1913, 1909, 1909,
           1916, 1919, 1915, 1907,
           1909, 1923, 1920, 1918,
           1909, 1914, 1911, NA,
           NA, 1920, 1921, 1907,
           1907, 1913, 1911, 1914,
           NA, 1908, 1909, 1903,
           1919, 1911, 1905, 1917,
           1909, NA, 1913, 1925,
           1921, 1907, 1908, 1918,
           1919, 1909, 1915, 1939),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Osteopaths <- tibble(
  occ = rep("Osteopaths", 48),
  state = state_vec,
  year = c(1911, 1941, 1903, 1901,
           1881, 1900, 1895, 1927,
           1909, 1907, 1899, 1905,
           1898, 1913, 1893, 1908,
           1919, 1914, NA, NA,
           1903, 1896, 1903, 1901,
           1919, 1925, NA, 1913,
           NA, 1907, 1907, 1909,
           1902, 1903, 1907, 1909,
           1914, NA, 1900, 1905,
           1873, 1907, 1904, 1903,
           1919, 1907, 1901, 1899),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Pharmacists <- tibble(
  occ = rep("Pharmacists", 48),
  state = state_vec,
  year = c(1931, 1935, 1891, 1891,
           1887, 1881, 1883, 1889,
           1881, 1889, 1881, 1899,
           1880, 1885, 1874, 1888,
           1877, 1902, 1885, 1885,
           1885, 1900, 1881, 1895,
           1887, 1901, 1875, 1877,
           1889, 1884, 1905, 1887,
           1884, 1899, 1891, 1887,
           1875, 1876, 1890, 1919,
           1907, 1892, 1894, 1886,
           1891, 1881, 1882, 1888),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Physicians <- tibble(
  occ = rep("Physicians", 48),
  state = state_vec,
  year = c(1911, 1901, 1903, 1876,
           1881, 1893, 1895, 1889,
           1894, 1899, 1877, 1897,
           1883, 1901, 1893, 1894,
           1895, 1892, 1894, NA,
           1883, 1882, 1901, 1889,
           NA, 1899, 1915, 1890,
           1889, 1879, NA, 1890,
           1896, 1908, 1895, 1877,
           1895, NA, 1900, 1889,
           1873, 1892, 1904, 1884,
           1909, 1882, 1897, 1899),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Teachers <- tibble(
  occ = rep("Teachers", 48),
  state = state_vec,
  year = c(NA, 1912, NA, 1851,
           NA, NA, NA, NA,
           NA, NA, 1913, NA,
           1846, 1873, 1838, NA,
           NA, NA, 1781, NA,
           1921, 1886, 1865, NA,
           1867, NA, NA, 1903,
           NA, 1897, 1917, NA,
           1825, NA, 1899, 1854,
           NA, NA, NA, 1855,
           1905, NA, 1888, NA,
           NA, NA, 1868, 1919),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

```{r}
Veterinarians <- tibble(
  occ = rep("Veterinarians", 48),
  state = state_vec,
  year = c(1915, 1923, 1915, 1893,
           1909, 1905, 1915, 1925,
           1908, 1921, 1899, 1905,
           1900, 1907, 1916, 1908,
           1905, 1895, 1904, NA,
           1900, NA, 1905, 1913,
           1905, 1919, NA, 1902,
           NA, 1895, 1903, 1895,
           1913, 1913, 1903, 1889,
           NA, NA, NA, 1905,
           1911, 1907, 1912, 1896,
           1907, NA, 1907, 1915),
  enact = c(1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1,
            1,1,1,1)
  ) %>%
  mutate(yrLength = year - min(year, na.rm = TRUE) + 1)
```

# Combine all occupations

```{r}
all_occs_raw <- rbind(Accountants, Architects, 
                  Barbers, Beauticians,
                  Chiropodists, Chiropractors,
                  Dentists, Embalmers,
                  Engineers, Nurses,
                  Optometrists, Osteopaths,
                  Pharmacists, Physicians,
                  Teachers, Veterinarians) 
# write_csv(all_occs_raw, "all_occs_raw.csv")
```

